apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-tools
  namespace: kube-acpodnaming
spec:
  selector:
    matchLabels:
      app: centos-tools
  replicas: 1
  template:
    metadata:
      labels:
        app: centos-tools
    spec:
      containers:
        - name: centos-tools
          image: quay.io/ooichman/centos-tools
